### ISSUE TITLE
Arabic

### ISSUE THREAD

**Issue by ahmed-tasaly** [wagyufari/dzikirqu-android#16]
**Assalam Alaykom**

Can you add Arabic language to the app ?

**Comment by ImBIOS** [comment]
Great idea. We aim to support any human language out there and want to let the community help a big part of the translation project.

**Comment by wagyufari** [comment]
Wa'alaikumsalam warahmatullah wabarakatuh,
InshaAllah we will be adding Arabic to the app very soon, but since it is not our primary task at the moment, please make do with the English language for now. Though, we will start translating the locale to Arabic as soon as possible.

Jazakallah khair
