### ISSUE TITLE
Activate the Branch Protection

### ISSUE THREAD

**Issue by ImBIOS** [wagyufari/dzikirqu-android#2]
![image](https://user-images.githubusercontent.com/41441643/182299897-3a9b337f-7b6a-4cc6-aca8-9553d9c5a7ca.png)
Apply these settings to this repository to protect the `master` branch from production code breaks.

**Comment by ImBIOS** [comment]
@wagyufari, I think we need to enable the discussion feature to create a better place for community discussion.

**Comment by wagyufari** [comment]
- Protection settings applied to master ✅ 
- Discussion feature has been enabled ✅
