### ISSUE TITLE
Attach APK to the release

### ISSUE THREAD

**Issue by Poussinou** [wagyufari/dzikirqu-android#21]
Hi,

Since your app can't be added to F-Droid due to a lot of non-floss components/libraries, would it be possible to add a signed release APK to your [releases](https://github.com/dzikirqu/dzikirqu-android/releases/) every time you tag a new release, so that people without access to the Play Store can still download, update, and use your app?

Thanks

**Comment by ImBIOS** [comment]
It was a great idea! 🚀

**Comment by Poussinou** [comment]
Since it has been done, I'm closing this Issue :)
