### ISSUE TITLE
Github Action workflows are going wrong

### ISSUE THREAD

**Issue by ImBIOS** [wagyufari/dzikirqu-android#5]
Somehow the GitHub workflow from #1 is constantly failing.

**Comment by dzakdzaks** [comment]
Yes, that is because some of our code affected by lint, we already working on this case. Temporary we can set lint abort error to false to ignore the lint and make gradle build success. Thanks for reminding

**Comment by dzakdzaks** [comment]
Already fixed in https://github.com/wagyufari/dzikirqu-android/pull/11
